/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { ensureOAuthProfileWithDefaults } from "../../definitions/login/index";
import {
  useMutation,
  useQueryClient,
  type UseMutationOptions,
} from "@tanstack/react-query";

export const useEnsureOAuthProfileWithDefaults = (mutationOptions?: {
  update?: UseMutationOptions<
    boolean,
    Error,
    {
      timezone: string;
      emailEnabled?: boolean;
      emailFrequency?: "immediate" | "daily" | "weekly";
    },
    unknown
  >;
}) => {
  const queryKey = ["ensureOAuthProfileWithDefaults"];
  const dependantQueryKeys = [["ensureOAuthProfileWithDefaults"], queryKey];
  const queryClient = useQueryClient();
  const update = useMutation(
    {
      ...mutationOptions?.update,
      mutationFn: async (data: {
        timezone: string;
        emailEnabled?: boolean;
        emailFrequency?: "immediate" | "daily" | "weekly";
      }) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await ensureOAuthProfileWithDefaults("update", data);
      },

      onSettled: (data, error, variables, onMutateResult, context) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
        mutationOptions?.update?.onSettled?.(
          data,
          error,
          variables,
          onMutateResult,
          context,
        );
      },
    },
    queryClient,
  );
  return { update };
};
