/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { profile, ProfileUpdateInput } from "../../definitions/profile/index";
import { useMutation, useQuery, useQueryClient, type QueryClient } from "@tanstack/react-query";

export const useManageUserProfile = () => {
  const queryKey = ["manageUserProfile"];
  const dependantQueryKeys = [["manageUserProfile"]];
  const queryClient = useQueryClient();
  const query = useQuery(
    {
      queryKey,
      queryFn: async () => await profile("read"),
    },
    queryClient,
  );
  const update = useMutation(
    {
      mutationFn: async (data: ProfileUpdateInput) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await profile("update", data);
      },
      // --- optimistic (codegen may inject logic here) ---
      onMutate: async () => {
        // __OPTIMISTIC_START__
        // The generator will replace this block when an optimistic config is present.
        // It must return an object that can be read by onError for rollback.
        return { snapshots: [] as Array<{ key: unknown[]; prev: unknown }> };
        // __OPTIMISTIC_END__
      },
      onError: (_err, _vars, ctx) => {
        // __ROLLBACK_START__
        // The generator will keep this rollback logic; it works with the snapshots returned by onMutate.
        if (ctx?.snapshots) {
          for (const { key, prev } of ctx.snapshots) {
            queryClient.setQueryData(key, prev);
          }
        }
        // __ROLLBACK_END__
      },
      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
      },
    },
    queryClient,
  );
  return { ...query, update }
};
export const getManageUserProfileQueryKey = () => {
  return ["manageUserProfile"] as const;
};
export const getManageUserProfileQueryOptions = () => {
  return {
    queryKey: getManageUserProfileQueryKey(),
    queryFn: async () => profile("read"),
  } as const;
};
export const prefetchManageUserProfile = () =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getManageUserProfileQueryOptions());
