/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { userProfileCrud } from "../../definitions/profile/index";
import { ProfileUpdateInput } from "../../definitions/common/profile";
import {
  useMutation,
  useQuery,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";

export const useProfile = () => {
  const queryKey = ["Profile"];
  const dependantQueryKeys = [["Profile"], queryKey];
  const queryClient = useQueryClient();
  const query = useQuery(
    { queryKey, queryFn: async () => await userProfileCrud("read", undefined) },
    queryClient,
  );
  const update = useMutation(
    {
      mutationFn: async (data: ProfileUpdateInput) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await userProfileCrud("update", data);
      },

      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
      },
    },
    queryClient,
  );
  return { ...query, update };
};
export const getProfileQueryKey = () => {
  return ["Profile"] as const;
};
export const getProfileQueryOptions = () => {
  return {
    queryKey: getProfileQueryKey(),
    queryFn: async () => userProfileCrud("read", undefined),
  } as const;
};
export const prefetchProfile = () => (qc: QueryClient) =>
  qc.prefetchQuery(getProfileQueryOptions());
