/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { getQuests } from "../../quest_actions";
import { getQuestDetails } from "../../quest_actions";
import { useMutation, useQuery, useQueryClient, type UseQueryResult, type UseMutationResult } from "@tanstack/react-query";

export interface UseGetQuests {
  (variantName: "getQuestDetails", ...args: [string]): UseQueryResult<{ id: string; title: string; description: string; details: string; }>;
  (variantName: null, ...args: []): UseQueryResult<{ id: string; title: string; description: string; }[]> & {
    create: UseMutationResult<boolean, Error, { title: string; description: string; }>
  };
}

export const useGetQuests: UseGetQuests = (variantName: "getQuestDetails" | null, ...args: unknown[]): any => {
  const queryKey = [variantName ? ({ "getQuestDetails": "getQuests.getQuestDetails" })[variantName] : "getQuests", ...args];
  const dependantQueryKeys = [["getQuests"], ["getQuests.getQuestDetails"]];
  const queryClient = useQueryClient();
  const query = useQuery(
    {
      queryKey,
      queryFn: async () => await (
        variantName === "getQuestDetails" ? getQuestDetails(
          ...args as [string]
        ) :
          getQuests("read")
      ),
    },
    queryClient,
  );
  const create = useMutation(
    {
      mutationFn: async (data: { title: string; description: string; }) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await getQuests("create", data);
      },
      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
      },
    },
    queryClient,
  );
  if (!variantName) {
    return { ...query, create }
  }
  return query
};
