/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { simpleAction } from "../sample_actions";
import { useQuery, useQueryClient } from "@tanstack/react-query";

export const useSimpleAction = (...args: [string]) => {
  const queryKey = ["simpleAction", ...args];
  const queryClient = useQueryClient();
  const query = useQuery(
    {
      queryKey,
      queryFn: async () => await simpleAction(...args),
    },
    queryClient,
  );
  return query;
};
