/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { insertQuest } from "../../definitions/create_quest/index";
import {
  useMutation,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";

export const useInsertQuest = () => {
  const dependantQueryKeys = [["insertQuest"]];
  const queryClient = useQueryClient();
  const create = useMutation(
    {
      mutationFn: async (
        data: import("/data/Work/HopeFlow/webapp/src/app/(dock)/create_quest/types").InsertQuestData,
      ) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await insertQuest("create", data);
      },

      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
      },
    },
    queryClient,
  );
  return { create };
};
export const getInsertQuestQueryKey = () => {
  return ["insertQuest"] as const;
};
export const getInsertQuestQueryOptions = () => {
  return {
    queryKey: getInsertQuestQueryKey(),
    queryFn: async () => insertQuest("read"),
  } as const;
};
export const prefetchInsertQuest = () => (qc: QueryClient) =>
  qc.prefetchQuery(getInsertQuestQueryOptions());
