/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { manageItems, Item } from "../../definitions/sample/sample_actions";
import { getItemById } from "../../definitions/sample/sample_actions";
import {
  useQuery,
  useQueryClient,
  type UseQueryResult,
  type UseMutationResult,
  type UseMutationOptions,
  type QueryClient,
} from "@tanstack/react-query";

export interface UseManageItems {
  (
    variantName: "getItemById",
    ...args: [number]
  ): UseQueryResult<undefined | Item>;
  (
    variantName: null,
    ...args: [
      ...[],
      (
        | {
            create?: UseMutationOptions<
              boolean,
              Error,
              Omit<Item, "id">,
              unknown
            >;
            update?: UseMutationOptions<boolean, Error, Item, unknown>;
            remove?: UseMutationOptions<
              boolean,
              Error,
              { id: number },
              unknown
            >;
          }
        | undefined
      )?,
    ]
  ): UseQueryResult<Item[]> & {
    create: UseMutationResult<boolean, Error, Omit<Item, "id">>;
    update: UseMutationResult<boolean, Error, Item>;
    remove: UseMutationResult<boolean, Error, { id: number }>;
  };
}

export const useManageItems: UseManageItems = (
  variantName: "getItemById" | null,
  ...args: unknown[]
): any => {
  const queryKey = [
    variantName
      ? { getItemById: "manageItems.getItemById" }[variantName]
      : "manageItems",
    ...args,
  ];
  const queryClient = useQueryClient();
  const query = useQuery(
    {
      queryKey,
      queryFn: async () =>
        await (variantName === "getItemById"
          ? getItemById(...(args as [number]))
          : manageItems("read", undefined)),
    },
    queryClient,
  );
  return query;
};
export const getManageItemsQueryKey = (
  variantName: "getItemById" | null,
  ...args: any[]
) => {
  return [
    variantName
      ? { getItemById: "manageItems.getItemById" }[variantName]
      : "manageItems",
    ...args,
  ] as const;
};
export const getManageItemsQueryOptions = (
  variantName: "getItemById" | null,
  ...args: any[]
) => {
  return {
    queryKey: getManageItemsQueryKey(variantName, ...args),
    queryFn: async () => {
      return variantName === "getItemById"
        ? getItemById(...(args as [number]))
        : manageItems("read", undefined, ...(args as []));
    },
  } as const;
};
export const prefetchManageItems: PrefetchManageItems =
  (variantName: "getItemById" | null, ...args: unknown[]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getManageItemsQueryOptions(variantName, ...args));

export interface PrefetchManageItems {
  (
    variantName: "getItemById",
    ...args: [number]
  ): (qc: QueryClient) => Promise<unknown>;
  (variantName: null, ...args: []): (qc: QueryClient) => Promise<unknown>;
}
