/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { simpleAction } from "../../definitions/sample/sample_actions";
import {
  useQuery,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";

export const useSimpleAction = (...args: [string]) => {
  const queryKey = ["simpleAction", ...args];
  const queryClient = useQueryClient();
  const query = useQuery(
    { queryKey, queryFn: async () => await simpleAction(...args) },
    queryClient,
  );
  return query;
};
export const getSimpleActionQueryKey = (...args: [string]) => {
  return ["simpleAction", ...args] as const;
};
export const getSimpleActionQueryOptions = (...args: [string]) => {
  return {
    queryKey: getSimpleActionQueryKey(...args),
    queryFn: async () => simpleAction(...args),
  } as const;
};
export const prefetchSimpleAction =
  (...args: [string]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getSimpleActionQueryOptions(...args));
