/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { linkNode } from "../../definitions/link/node";
import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationOptions,
  type QueryClient,
} from "@tanstack/react-query";

export const useLinkNode = (
  ..._args: [
    ...[{ linkCode: string }],
    (
      | {
          create?: UseMutationOptions<
            boolean,
            Error,
            {
              referer: import("/Users/saeed/Projects/webapp/src/app/(nodock)/link/[linkCode]/components/ReflowTree").SocialMediaName;
            },
            unknown
          >;
        }
      | undefined
    )?,
  ]
) => {
  const args = _args.slice(0, 1) as [{ linkCode: string }];
  const mutationOptions = _args[1] as
    | {
        create?: UseMutationOptions<
          boolean,
          Error,
          {
            referer: import("/Users/saeed/Projects/webapp/src/app/(nodock)/link/[linkCode]/components/ReflowTree").SocialMediaName;
          },
          unknown
        >;
      }
    | undefined;
  const queryKey = ["linkNode", ...args];
  const dependantQueryKeys = [["linkNode"], ["linkTimeline"], queryKey];
  const queryClient = useQueryClient();
  const query = useQuery(
    {
      queryKey,
      queryFn: async () => await linkNode("read", undefined, ...args),
    },
    queryClient,
  );
  const create = useMutation(
    {
      ...mutationOptions?.create,
      mutationFn: async (data: {
        referer: import("/Users/saeed/Projects/webapp/src/app/(nodock)/link/[linkCode]/components/ReflowTree").SocialMediaName;
      }) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await linkNode("create", data, ...args);
      },

      onSettled: (data, error, variables, onMutateResult, context) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
        mutationOptions?.create?.onSettled?.(
          data,
          error,
          variables,
          onMutateResult,
          context,
        );
      },
    },
    queryClient,
  );
  return { ...query, create };
};
export const getLinkNodeQueryKey = (...args: [{ linkCode: string }]) => {
  return ["linkNode", ...args] as const;
};
export const getLinkNodeQueryOptions = (...args: [{ linkCode: string }]) => {
  return {
    queryKey: getLinkNodeQueryKey(...args),
    queryFn: async () => linkNode("read", undefined, ...args),
  } as const;
};
export const prefetchLinkNode =
  (...args: [{ linkCode: string }]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getLinkNodeQueryOptions(...args));
