/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { linkNode } from "../../definitions/link/node";
import { useMutation, useQueryClient } from "@tanstack/react-query";

export const useLinkNode = (...args: [{ linkCode: string }]) => {
  const queryKey = ["linkNode", ...args];
  const dependantQueryKeys = [["linkNode"], ["linkTimeline"], queryKey];
  const queryClient = useQueryClient();
  const create = useMutation(
    {
      mutationFn: async (data: {
        referer: import("/Users/saeed/Projects/webapp/src/app/(nodock)/link/[linkCode]/components/ReflowTree").SocialMediaName;
      }) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await linkNode("create", data, ...args);
      },

      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
      },
    },
    queryClient,
  );
  return { create };
};
