/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { linkStatsCard } from "../../definitions/link/stats";
import { LinkStatsCardReadParams } from "../../definitions/link/types";
import {
  useQuery,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";

export const useLinkStatsCard = (...args: [LinkStatsCardReadParams]) => {
  const queryKey = ["linkStatsCard", ...args];
  const queryClient = useQueryClient();
  const query = useQuery(
    { queryKey, queryFn: async () => await linkStatsCard(...args) },
    queryClient,
  );
  return query;
};
export const getLinkStatsCardQueryKey = (
  ...args: [LinkStatsCardReadParams]
) => {
  return ["linkStatsCard", ...args] as const;
};
export const getLinkStatsCardQueryOptions = (
  ...args: [LinkStatsCardReadParams]
) => {
  return {
    queryKey: getLinkStatsCardQueryKey(...args),
    queryFn: async () => linkStatsCard(...args),
  } as const;
};
export const prefetchLinkStatsCard =
  (...args: [LinkStatsCardReadParams]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getLinkStatsCardQueryOptions(...args));
