/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { linkTimeline } from "../../definitions/link/timeline";
import {
  LinkTimelineCreateInput,
  LinkTimelineReactionInput,
  LinkTimelineReadParams,
} from "../../definitions/link/types";
import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationOptions,
  type QueryClient,
} from "@tanstack/react-query";

export const useLinkTimeline = (
  ..._args: [
    ...[LinkTimelineReadParams],
    (
      | {
          create?: UseMutationOptions<
            boolean,
            Error,
            LinkTimelineCreateInput,
            unknown
          >;
          update?: UseMutationOptions<
            boolean,
            Error,
            LinkTimelineReactionInput,
            unknown
          >;
        }
      | undefined
    )?,
  ]
) => {
  const args = _args.slice(0, 1) as [LinkTimelineReadParams];
  const mutationOptions = _args[1] as
    | {
        create?: UseMutationOptions<
          boolean,
          Error,
          LinkTimelineCreateInput,
          unknown
        >;
        update?: UseMutationOptions<
          boolean,
          Error,
          LinkTimelineReactionInput,
          unknown
        >;
      }
    | undefined;
  const queryKey = ["linkTimeline", ...args];
  const dependantQueryKeys = [["linkTimeline"], ["linkStatsCard"], queryKey];
  const queryClient = useQueryClient();
  const query = useQuery(
    {
      queryKey,
      queryFn: async () => await linkTimeline("read", undefined, ...args),
    },
    queryClient,
  );
  const create = useMutation(
    {
      ...mutationOptions?.create,
      mutationFn: async (data: LinkTimelineCreateInput) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await linkTimeline("create", data, ...args);
      },

      onSettled: (data, error, variables, onMutateResult, context) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
        mutationOptions?.create?.onSettled?.(
          data,
          error,
          variables,
          onMutateResult,
          context,
        );
      },
    },
    queryClient,
  );
  const update = useMutation(
    {
      ...mutationOptions?.update,
      mutationFn: async (data: LinkTimelineReactionInput) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await linkTimeline("update", data, ...args);
      },

      onSettled: (data, error, variables, onMutateResult, context) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
        mutationOptions?.update?.onSettled?.(
          data,
          error,
          variables,
          onMutateResult,
          context,
        );
      },
    },
    queryClient,
  );
  return { ...query, create, update };
};
export const getLinkTimelineQueryKey = (...args: [LinkTimelineReadParams]) => {
  return ["linkTimeline", ...args] as const;
};
export const getLinkTimelineQueryOptions = (
  ...args: [LinkTimelineReadParams]
) => {
  return {
    queryKey: getLinkTimelineQueryKey(...args),
    queryFn: async () => linkTimeline("read", undefined, ...args),
  } as const;
};
export const prefetchLinkTimeline =
  (...args: [LinkTimelineReadParams]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getLinkTimelineQueryOptions(...args));
