/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by .tmp-hooks/gen_server_action_hooks.js
import { linkTimeline } from "../../definitions/link/timeline";
import {
  LinkTimelineCreateInput,
  LinkTimelineReactionInput,
  LinkTimelineReadParams,
} from "../../definitions/link/types";
import {
  useMutation,
  useQuery,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";

export const useLinkTimeline = (...args: [LinkTimelineReadParams]) => {
  const queryKey = ["linkTimeline", ...args];
  const dependantQueryKeys = [["linkTimeline"], queryKey];
  const queryClient = useQueryClient();
  console.log("useLinkTimeline", queryKey);
  /*
  [
    "linkTimeline",
    {
        "linkCode": "plf-t977t-l6i1"
    }
  ]
  */
  const query = useQuery(
    {
      queryKey,
      queryFn: async () => await linkTimeline("read", undefined, ...args),
    },
    queryClient,
  );
  const create = useMutation(
    {
      mutationFn: async (data: LinkTimelineCreateInput) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await linkTimeline("create", data, ...args);
      },

      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) => {
          console.log("invalidateQueries", queryKey);
          // [
          //   "linkTimeline"
          // ]
          queryClient.invalidateQueries({ queryKey });
        });
      },
    },
    queryClient,
  );
  const update = useMutation(
    {
      mutationFn: async (data: LinkTimelineReactionInput) => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.cancelQueries({ queryKey }),
        );
        return await linkTimeline("update", data, ...args);
      },

      onSettled: () => {
        dependantQueryKeys.forEach((queryKey) =>
          queryClient.invalidateQueries({ queryKey }),
        );
      },
    },
    queryClient,
  );
  return { ...query, create, update };
};
export const getLinkTimelineQueryKey = (...args: [LinkTimelineReadParams]) => {
  return ["linkTimeline", ...args] as const;
};
export const getLinkTimelineQueryOptions = (
  ...args: [LinkTimelineReadParams]
) => {
  return {
    queryKey: getLinkTimelineQueryKey(...args),
    queryFn: async () => linkTimeline("read", undefined, ...args),
  } as const;
};
export const prefetchLinkTimeline =
  (...args: [LinkTimelineReadParams]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getLinkTimelineQueryOptions(...args));
