/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_route_helpers.ts
import { useRouter } from "next/navigation";
import { useCallback } from "react";

const toStringParam = (v: unknown) =>
  encodeURIComponent(typeof v === "string" ? v : JSON.stringify(v));
const toPathParams = <T extends { [key: string]: unknown }>(
  props: T,
  parts: Array<
    { part: keyof T & string; isParam: true } | { part: string; isParam: false }
  >,
) => {
  return Array.from(parts).flatMap(({ part, isParam }): string[] => {
    if (!isParam) return [part];
    const v = props[part as keyof T];
    if (v === undefined) return ["undefined"];
    if (Array.isArray(v)) return v.map(toStringParam);
    return [toStringParam(v)];
  });
};
const toSearchParams = <T extends { [key: string]: unknown }>(
  props: T,
  keys: Array<keyof T & string>,
) => {
  const result = Array.from(keys).flatMap((key): Array<string> => {
    const value = props[key];
    if (value === undefined) return [];
    if (Array.isArray(value))
      return value.map((e) => `${key}=${toStringParam(e)}`);
    return [`${key}=${toStringParam(value)}`];
  });
  if (result.length === 0) return "";
  return `?${result.join("&")}`;
};

// Corresponding to src/app/(root)/page.tsx
export const useGotoIndex = () => {
  const router = useRouter();
  return useCallback(() => router.push("/"), [router]);
};

// Corresponding to src/app/home/page.tsx
export const useGotoHome = () => {
  const router = useRouter();
  return useCallback(() => router.push("/home"), [router]);
};

// Corresponding to src/app/login/page.tsx
export const useGotoLogin = () => {
  const router = useRouter();
  return useCallback(
    (props: { url?: string | undefined; }) =>
      router.push(
        [
          "",
          ...toPathParams(props, [{ "part": "login", "isParam": false }]),
        ].join("/") + toSearchParams(props, ["url"]),
      ),
    [router],
  );
};

// Corresponding to src/app/link/[linkCode]/page.tsx
export const useGotoLink = () => {
  const router = useRouter();
  return useCallback(
    (props: { linkCode: string; }) =>
      router.push(
        [
          "",
          ...toPathParams(props, [{ "part": "link", "isParam": false }, { "part": "linkCode", "isParam": true }]),
        ].join("/"),
      ),
    [router],
  );
};

export interface UseGoto {
  (routeName: "Index"): () => void;
  (routeName: "Home"): () => void;
  (routeName: "Login"): (props: { url?: string | undefined; }) => void;
  (routeName: "Link"): (props: { linkCode: string; }) => void;
}

export const useGoto: UseGoto = (routeName: "Index" | "Home" | "Login" | "Link"): any => {
  const __route0 = useGotoIndex();
  const __route1 = useGotoHome();
  const __route2 = useGotoLogin();
  const __route3 = useGotoLink();
  switch (routeName) {
    case "Index": return __route0;
    case "Home": return __route1;
    case "Login": return __route2;
    case "Link": return __route3;
  }
};
