// This file is auto-generated by scripts/gen_route_helpers.ts
import { useRouter } from "next/navigation";
import { useCallback } from "react";

const toStringParam = (v: unknown) =>
  encodeURIComponent(typeof v === "string" ? v : JSON.stringify(v));
const toPathParams = <T extends { [key: string]: unknown }>(
  props: T,
  parts: Array<
    { part: keyof T & string; isParam: true } | { part: string; isParam: false }
  >,
) => {
  return Array.from(parts).flatMap(({ part, isParam }): string[] => {
    if (!isParam) return [part];
    const v = props[part as keyof T];
    if (v === undefined) return ["undefined"];
    if (Array.isArray(v)) return v.map(toStringParam);
    return [toStringParam(v)];
  });
};
const toSearchParams = <T extends { [key: string]: unknown }>(
  props: T,
  keys: Array<keyof T & string>,
) => {
  const result = Array.from(keys).flatMap((key): Array<string> => {
    const value = props[key];
    if (value === undefined) return [];
    if (Array.isArray(value))
      return value.map((e) => `${key}=${toStringParam(e)}`);
    return [`${key}=${toStringParam(value)}`];
  });
  if (result.length === 0) return "";
  return `?${result.join("&")}`;
};

// Corresponding to src/app/(root)/page.tsx
export const useGotoIndex = () => {
  const router = useRouter();
  return useCallback(() => router.push("/"), [router]);
};

// Corresponding to src/app/login/page.tsx
export const useGotoLogin = () => {
  const router = useRouter();
  return useCallback(
    (props: { url?: string | undefined; }) =>
      router.push(
        [
          "",
          ...toPathParams(props, [{ "part": "login", "isParam": false }]),
        ].join("/") + toSearchParams(props, ["url"]),
      ),
    [router],
  );
};

export interface UseGoto {
  (routeName: "Index"): () => void;
  (routeName: "Login"): (props: { url?: string | undefined; }) => void;
}

export const useGoto: UseGoto = (routeName: "Index" | "Login"): any => {
  switch (routeName) {
    case "Index": return useGotoIndex();
    case "Login": return useGotoLogin();
  }
};
