/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by scripts/gen_server_action_hooks.ts
import { quests } from "../../definitions/home/index";
import {
  useQuery,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";

export const useQuests = (...args: [{ offset: number; limit: number }]) => {
  const queryKey = ["quests", ...args];
  const queryClient = useQueryClient();
  const query = useQuery(
    { queryKey, queryFn: async () => await quests(...args) },
    queryClient,
  );
  return query;
};
export const getQuestsQueryKey = (
  ...args: [{ offset: number; limit: number }]
) => {
  return ["quests", ...args] as const;
};
export const getQuestsQueryOptions = (
  ...args: [{ offset: number; limit: number }]
) => {
  return {
    queryKey: getQuestsQueryKey(...args),
    queryFn: async () => quests(...args),
  } as const;
};
export const prefetchQuests =
  (...args: [{ offset: number; limit: number }]) =>
  (qc: QueryClient) =>
    qc.prefetchQuery(getQuestsQueryOptions(...args));
